// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pvc8dLkeqiOiIwykPq_Wv_UDeiEQQ7I',
    appId: '1:412608581858:web:f4042803da631322184ebb',
    messagingSenderId: '412608581858',
    projectId: 'battledogs-18c63',
    authDomain: 'battledogs-18c63.firebaseapp.com',
    storageBucket: 'battledogs-18c63.firebasestorage.app',
    measurementId: 'G-Y1Y8YJEVYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChP4rz-B2rurpfgtAFJMP6KS_uAb8hMso',
    appId: '1:412608581858:android:ab3b7336a2a50ba6184ebb',
    messagingSenderId: '412608581858',
    projectId: 'battledogs-18c63',
    storageBucket: 'battledogs-18c63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1CKm7n7AHmog1_0soAHwN2RUNu5v0zY',
    appId: '1:412608581858:ios:836972d2a7b50b5b184ebb',
    messagingSenderId: '412608581858',
    projectId: 'battledogs-18c63',
    storageBucket: 'battledogs-18c63.firebasestorage.app',
    iosBundleId: 'com.example.battleDogs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0pvc8dLkeqiOiIwykPq_Wv_UDeiEQQ7I',
    appId: '1:412608581858:web:98ef466be6921dd7184ebb',
    messagingSenderId: '412608581858',
    projectId: 'battledogs-18c63',
    authDomain: 'battledogs-18c63.firebaseapp.com',
    storageBucket: 'battledogs-18c63.firebasestorage.app',
    measurementId: 'G-W10DPSEVRR',
  );

}